// Class created to hold Debug anonymouse code for time save
public class DebugAnonymouseCode {
/*

//For Testing purpose pass configuration Heroku Name in where condition
List<Configuration_Heroku__c> confi=[Select Id,Date__c,Fields_1_APIs__c,Fields_2_APIs__c,Fields_3_APIs__c,Fields_4_APIs__c,Fields_5_APIs__c,Filter_Condition_1__c,Filter_Condition_2__c,Filter_Condition_3__c,Filter_Condition_4__c,Filter_Condition_5__c,Object_1_API_Name__c,Object_2_API_Name__c,Object_3_API_Name__c,Object_4_API_Name__c,Object_5_API_Name__c,Runs_on__c,Schedule_By__c,Starts_At__c,Status__c from Configuration_Heroku__c where name='H-00094'];
 HerokuSyncBatchApexHelper.getHerokuObjData(confi);

// Run Below code to revert back to false for Testing purpose 
for(opportunity c:[Select id from opportunity]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(contact c:[Select id from contact]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(account c:[Select id from account]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(case c:[Select id from case]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}
for(lead c:[Select id from lead]){
    c.Ready_to_migrate_to_Heroku__c=false;
    update c;
}



 */
}